### ISSUE TITLE
Can't complete "Weapons of Choice" quest

### ISSUE THREAD

**Issue by danjking** [The-Barrens-org/Bugtracker#10]
Current behaviour: Can't complete "Weapons of Choice" quest - I killed the right mobs, got the 3 drops (Razormane Backstabber, Charred Razormane Wand, Razormane War Shield) but I was unable to complete the quest - the question mark was grayed out.

Expected behaviour: I should be able to complete the quest when I loot the 3 items.

Steps to reproduce the problem: Kill the mobs, get the drops, try to complete

Include the ID for game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, achievements, skills: NA

**Comment by Underminus** [comment]
This is actually a Client side bug. You can either Drop the quest and pick it up again or sell the items to a vendor and buy them back or place them in your bank and take them out again to fix it.

**Comment by eXpLethora** [comment]
Yeah this happens usually because u loot more then one of the item and then you drop the first one you picked up. Ad easy as abandon and get quest again.
