### ISSUE TITLE
Elemental Invasion Bosses - Evade

### ISSUE THREAD

**Issue by Tamosheik** [The-Barrens-org/Bugtracker#23]
**Patch:**
1.05

**Current behaviour:**
When attacking the NPC Princess Tempestria as part of the elemental invasion, she evades and returns to the nearest portal before continuing to patrol. Aggroing her (even in melee range) will cause her to exhibit the same behaviour.

**Expected behaviour:**
It should be possible to kill Princess Tempestria

**Steps to reproduce the problem:**
Attack Princess Tempestria

**IDs**
[NPC] Princess Tempestria (14457)

**Source**
https://classicdb.ch/?npc=14457

**Comment by Tamosheik** [comment]
Tested Baron Charr . He exhibits the same behaviour.

IDs
[NPC] Baron Char (14461)

**Comment by Nolin7777** [comment]
fixed
