### ISSUE TITLE
Gurubashi arena

### ISSUE THREAD

**Issue by imtrollingu** [The-Barrens-org/Bugtracker#26]
I have been on for the last three days for 3 hours or more in STV and the Gurubashi arena event never goes off. I'm at the arena just before the hour finishes and just after. Today I was here from 6-9 pm. NPC doesn't move or trigger the event.

**Comment by igreus** [comment]
Yeah +1 - I've just reported this too

**Comment by flak0s** [comment]
Have you been in the zone for 3 hours consecutively? Start time won't necessarily be on the hour

**Comment by igreus** [comment]
While at work, I was afk in the arena for about 5 hours - no sign of chest or shout
________________________________

**Comment by imtrollingu** [comment]
Yes. I have had nights that I have been there for about 5 hours. It was
working a few weeks back but then just stopped.
