### ISSUE TITLE
Broodlord head not dropping despite quest in log

### ISSUE THREAD

**Issue by Harrock1** [The-Barrens-org/Bugtracker#38]
Patch:
1.09

Current behaviour:
Head of the Broodlord Lashlayer is not dropping despite having the quest "Only One May Rise" for the last several weeks.

Expected behaviour:
One Head of the Broodlord Lashlayer should drop per week pending someone inside the raid has the quest in their questlog.

Steps to reproduce the problem:

Pickup quest "Only One May Rise" from silithus (id=8288)
Head into BWL, slay the 3rd boss, Broodlord Lashlayer
Check loot.

IDs
http://classicdb.ch/?quest=8288
https://classicdb.ch/?item=20383

Source
https://i.imgur.com/0ihyol9.jpg

**Comment by BarrensJerk** [comment]
Still not dropping quest item

**Comment by Nolin7777** [comment]
fixed
