### ISSUE TITLE
Naxx - Instructor Razuvious - Unable to heal Deathknight Understudy

### ISSUE THREAD

**Issue by Cheelout** [The-Barrens-org/Bugtracker#41]
What happens: Understudy is Mind Controlled, Neither faction can heal

What is meant to Happen: Understudy is meant to be able to be healed when Mind Controlled, Core mechanic of the fight

Source: http://wowwiki.wikia.com/wiki/Instructor_Razuvious_(original)

**Comment by Nolin7777** [comment]
Fixed
