### ISSUE TITLE
Overlord Wyrmthalak (No Loot)

### ISSUE THREAD

**Issue by Tamosheik** [The-Barrens-org/Bugtracker#43]
Patch:
1.12

Current behaviour:
Killing Overlord Wyrmthalak sometimes awards no loot

Expected behaviour:
The boss should drop loot

Steps to reproduce the problem:
Kill Overlord Wyrmthalak from LBRS. The Bug is intermittent.

IDs
[NPC] Overlord Wyrmthalak (9568)

Source
http://classicdb.ch/?npc=9568

**Comment by Nolin7777** [comment]
Can't reproduce sorry

**Comment by Nolin7777** [comment]
fixed
