### ISSUE TITLE
Disenchant window loot issue

### ISSUE THREAD

**Issue by Kolinahr** [The-Barrens-org/Bugtracker#5]
I can disenchant items. I even can receive the enchantment loot. However, when I mouse over the loot window to click and receive mats, I am incapable of doing so. What I do is disenchant then have to move my character to make the loot window disappear.

**Comment by Underminus** [comment]
Are you using any add-ons? If so try turning off Add-ons and then disenchanting something.

**Comment by Kolinahr** [comment]
I am not using any add-ons. (other than the stock Blizzard ones)

**Comment by Soopra** [comment]
also disenchanting while inventory is full deletes the disenchant material D:
