### ISSUE TITLE
Global respawn rate

### ISSUE THREAD

**Issue by Sebbyyy** [The-Barrens-org/Bugtracker#7]
Every mob seems to respawn too quickly - you cannot clear a cave or struggle with a couple of mobs without everything respawning.

**Comment by Underminus** [comment]
Please list the specific mobs you are encountering that are respawning too fast.

**Comment by Sebbyyy** [comment]
I have noticed across all mobs i think. But the ones I just had a problem with was the ferocious/mountain yetis in southern part of alterac mountains.
